Repository pysal/spreg, pull requests merged in 2024-09, with the labels that each got.

#149 build docs with 3.12 environment
  .github/workflows/build_docs.yml
  ci/312-latest.yaml
  ci/39-latest.yaml
Labels: docs, github_actions

#154 update `environment.yml` & remove `.coveragerc`
  .coveragerc
  environment.yml
Labels: maint/admin

#156 `ruff` format repo
  .pre-commit-config.yaml
  pyproject.toml
  spreg/__init__.py
  spreg/dgp.py
  spreg/diagnostics.py
  spreg/diagnostics_panel.py
  spreg/diagnostics_sp.py
  spreg/diagnostics_sur.py
  spreg/diagnostics_tsls.py
  spreg/error_sp.py
  spreg/error_sp_het.py
  spreg/error_sp_het_regimes.py
  spreg/error_sp_hom.py
  spreg/error_sp_hom_regimes.py
  spreg/error_sp_regimes.py
  spreg/ml_error.py
  spreg/ml_error_regimes.py
  spreg/ml_lag.py
  spreg/ml_lag_regimes.py
  spreg/ols.py
  spreg/ols_regimes.py
  spreg/output.py
  spreg/panel_fe.py
  spreg/panel_re.py
  spreg/panel_utils.py
  spreg/probit.py
  spreg/regimes.py
  spreg/skater_reg.py
  spreg/sp_panels.py
  spreg/sputils.py
  spreg/summary_output.py
  spreg/sur.py
  spreg/sur_error.py
  spreg/sur_utils.py
  spreg/twosls.py
  spreg/twosls_regimes.py
  spreg/twosls_sp.py
  spreg/twosls_sp_regimes.py
  spreg/user_output.py
  spreg/utils.py
Labels: maint/admin

#158 Updating spreg to 1.7
  .github/workflows/unittests.yml
  ci/310-latest.yaml
  ci/310-min.yaml
  ci/311-latest.yaml
  ci/312-latest.yaml
  ci/39-latest.yaml
  docs/_static/references.bib
  docs/api.rst
  spreg/__init__.py
  spreg/diagnostics.py
  spreg/diagnostics_sp.py
  spreg/error_sp_het.py
  spreg/error_sp_hom.py
  spreg/ml_lag.py
  spreg/ml_lag_regimes.py
  spreg/nslx.py
  spreg/ols.py
  spreg/ols_regimes.py
  spreg/output.py
  spreg/skater_reg.py
  spreg/sputils.py
  spreg/tests/test_nslx.py
  spreg/twosls.py
  spreg/twosls_regimes.py
  spreg/twosls_sp.py
  spreg/twosls_sp_regimes.py
  spreg/user_output.py
  spreg/utils.py
Labels: bug, enhancement
